MPP/Lab4/Lab4/Models/CreateFacultyViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Lab4.Models;

public class CreateFacultyViewModel
{
    [Required]
    public string? Name { get; set; }
}

MPP/Lab4/Lab4/Models/CreateGroupViewModel.cs
using System.ComponentModel.DataAnnotations;
using DAL.Models;

namespace Lab4.Models;

public class CreateGroupViewModel
{
    [Required]
    public string? Name { get; set; }
    
    public IEnumerable<Faculty>? Faculties { get; set; }
    
    [Required]
    public string? SelectedFacultyId { get; set; }
}

MPP/Lab4/Lab4/Models/CreateStudentViewModel.cs
using System.ComponentModel.DataAnnotations;
using DAL.Models;

namespace Lab4.Models;

public class CreateStudentViewModel
{
    [Required]
    public string? Name { get; set; }

    public IEnumerable<Group>? Groups;
    
    [Required] 
    public string? SelectedGroupId { get; set; }
}

MPP/Lab4/Lab4/Models/CreateSubjectViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Lab4.Models;

public class CreateSubjectViewModel
{
    [Required]
    public string? Name { get; set; }
}

MPP/Lab4/Lab4/Models/ErrorViewModel.cs
namespace Lab4.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MPP/Lab4/Lab4/Models/HomeIndexViewModel.cs
using DAL.Models;

namespace Lab4.Models;

public class HomeIndexViewModel
{
    public IEnumerable<Student>? Students { get; set; }
}

MPP/Lab4/Lab4/Models/StudentInfoViewModel.cs
using System.ComponentModel.DataAnnotations;
using DAL.Models;

namespace Lab4.Models;

public class StudentInfoViewModel
{
    public Student? Student { get; set; }

    public IEnumerable<Subject>? Subjects;

    [Required]
    public string? SelectedSubjectId { get; set; }
}

MPP/Lab4/Lab4/Controllers/FacultyController.cs
using BL.Interfaces;
using Lab4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab4.Controllers;

public class FacultyController : Controller
{
    private readonly ILogger<FacultyController> _logger;
    private readonly IFacultyManager _facultyManager;
    
    public FacultyController(ILogger<FacultyController> logger, 
        IFacultyManager facultyManager)
    {
        _logger = logger;
        _facultyManager = facultyManager;
    }

    public IActionResult Index()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Index(CreateFacultyViewModel facultyViewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(facultyViewModel);
        }

        _facultyManager.CreateFaculty(facultyViewModel.Name!);
        return View(null);
    }
}

MPP/Lab4/Lab4/Controllers/GroupController.cs
using BL.Interfaces;
using DAL.Models;
using Lab4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab4.Controllers;

public class GroupController : Controller
{
    private readonly ILogger<GroupController> _logger;
    private readonly IFacultyManager _facultyManager;
    private readonly IGroupManager _groupManager;

    public GroupController(
        ILogger<GroupController> logger, 
        IFacultyManager facultyManager, 
        IGroupManager groupManager)
    {
        _logger = logger;
        _facultyManager = facultyManager;
        _groupManager = groupManager;
    }

    public IActionResult Index()
    {
        List<Faculty> allFaculties = _facultyManager.GetAllFaculties().ToList();
        
        var createGroupViewModel = new CreateGroupViewModel
        {
            Faculties = allFaculties
        };
        
        return View(createGroupViewModel);
    }

    [HttpPost]
    public IActionResult Index(CreateGroupViewModel groupViewModel)
    {
        groupViewModel.Faculties = _facultyManager.GetAllFaculties().ToList();
        if (!ModelState.IsValid)
        {
            return View(groupViewModel);
        }

        _groupManager.CreateGroup(groupViewModel.Name!, groupViewModel.SelectedFacultyId!);
        
        return View(groupViewModel);
    }
}

MPP/Lab4/Lab4/Controllers/HomeController.cs
using System.Collections;
using System.Diagnostics;
using BL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Lab4.Models;

namespace Lab4.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IStudentManager _studentManager;

    public HomeController(ILogger<HomeController> logger, IStudentManager studentManager)
    {
        _logger = logger;
        _studentManager = studentManager;
    }

    [HttpGet]
    public IActionResult Index()
    {
        IEnumerable<Student> students = _studentManager.GetAllStudents();
        
        var model = new HomeIndexViewModel
        {
            Students = students
        };
        
        return View(model);
    }

    [HttpGet]
    public IActionResult Sort()
    {
        IEnumerable<Student> students = _studentManager.GetAllStudents().OrderBy(s => s.Name);
        var model = new HomeIndexViewModel()
        {
            Students = students
        };
        return View("Index", model);
    }

    [HttpGet]
    public IActionResult Filter(string filterName)
    {
        IEnumerable<Student> students = _studentManager.GetAllStudents().Where(s => s.Name!.Contains(filterName));
        var model = new HomeIndexViewModel
        {
            Students = students
        };
        return View("Index", model);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }

    [HttpDelete]
    public IActionResult Delete(string id)
    {
        _studentManager.Delete(id);
        return RedirectToAction("Index");
    }
}

MPP/Lab4/Lab4/Controllers/StudentController.cs
using BL.Interfaces;
using DAL.Models;
using Lab4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab4.Controllers;

public class StudentController : Controller
{
    private readonly IStudentManager _studentManager;
    private readonly ISubjectManager _subjectManager;
    private readonly IGroupManager _groupManager;
    
    public StudentController(
        IStudentManager studentManager, 
        IGroupManager groupManager, 
        ISubjectManager subjectManager)
    {
        _studentManager = studentManager;
        _groupManager = groupManager;
        _subjectManager = subjectManager;
    }

    [HttpGet]
    public IActionResult Index()
    {
        List<Group> groups = _groupManager.GetAllGroups().ToList();

        var viewModel = new CreateStudentViewModel
        {
            Groups = groups
        };
        return View(viewModel);
    }

    [HttpGet]
    public IActionResult Info(string? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        Student student = _studentManager.FindById(id);
        IEnumerable<Subject> subjects = _subjectManager.GetSubjects();

        var studentInfoViewModel = new StudentInfoViewModel
        {
            Student = student,
            Subjects = subjects
        };
        
        return View(studentInfoViewModel);
    }

    [HttpPost]
    public IActionResult Index(CreateStudentViewModel createStudentViewModel)
    {
        createStudentViewModel.Groups = _groupManager.GetAllGroups().ToList();
        if (!ModelState.IsValid)
        {
            return View(createStudentViewModel);
        }

        _studentManager.CreateStudent(createStudentViewModel.Name!, createStudentViewModel.SelectedGroupId!);
        return View(createStudentViewModel);
    }

    [HttpPost]
    public IActionResult Info(string subjectId, string studentId)
    {
        _studentManager.AddSubject(studentId, subjectId);

        Student student = _studentManager.FindById(studentId);
        IEnumerable<Subject> subjects = _subjectManager.GetSubjects();

        var studentInfoViewModel = new StudentInfoViewModel
        {
            Student = student,
            Subjects = subjects
        };

        return View(studentInfoViewModel);
    }
}

MPP/Lab4/Lab4/Controllers/SubjectController.cs
using BL.Interfaces;
using Lab4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab4.Controllers;

public class SubjectController : Controller
{
    private readonly ISubjectManager _subjectManager;
    
    public SubjectController(ISubjectManager subjectManager)
    {
        _subjectManager = subjectManager;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(CreateSubjectViewModel subjectViewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(subjectViewModel);
        }

        _subjectManager.CreateSubject(subjectViewModel.Name!);
        return View(null);
    }
}

MPP/Lab4/Lab4/Views/Faculty/Index.cshtml
@model CreateFacultyViewModel;

@{
    ViewData["Title"] = "Create Faculty";
}

<h1> Create new Faculty </h1>

<form method="post">
    <div class="form">
        <label class="form-label" for="name">Faculty Name</label>
        <input class="form-control" type="text" name="name" id="name" />
        <span asp-validation-for="Name" class="text-danger"></span><br/>
        <button type="submit" class="btn btn-primary mt-2">Create</button>
    </div>
</form>

MPP/Lab4/Lab4/Views/Group/Index.cshtml
@model CreateGroupViewModel;

@{
    ViewData["Title"] = "Create Group";
}

<form method="post">
    <div class="form">
        <label class="form-label" for="name">Group Name</label>
        <input class="form-control" type="text" name="name" id="name" />
        <span asp-validation-for="Name" class="text-danger"></span><br/>
        <select class="form-control"
                asp-items="@(new SelectList(Model.Faculties, "Id", "Name"))"
                name="selectedFacultyId" 
                id="selectedFacultyId">
        </select>
        <span asp-validation-for="SelectedFacultyId" class="text-danger"></span><br/>
        <button type="submit" class="btn btn-primary mt-2">Create</button>
    </div>
</form>

MPP/Lab4/Lab4/Views/Home/Index.cshtml
@using DAL.Models
@model HomeIndexViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-3">
        <a class="text-dark" asp-area="" asp-controller="Group" asp-action="Index">
            Create new Group
        </a>
    </div>
    <div class="col-3">
        <a class="text-dark" asp-area="" asp-controller="Student" asp-action="Index">
            Create new Student
        </a>
    </div>
    <div class="col-3">
        <a class="text-dark" asp-area="" asp-controller="Faculty" asp-action="Index">
            Create new Faculty
        </a>
    </div>
    <div class="col-3">
        <a class="text-dark" asp-area="" asp-controller="Subject" asp-action="Index">
            Create new Subject
        </a>
    </div>
</div>

<div class="row mt-5">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Student Id</th>
            <th scope="col"><a asp-controller="Home" asp-action="Sort">Name</a></th>
            <th scope="col">Group</th>
            <th scope="col">Subjects</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><a asp-action="Index">Remove filters</a></td>
            <td>
                <form method="get" asp-action="Filter">
                    <div class="form">
                        <input type="text" name="filterName" id="filterName"/>
                        <button type="submit" class="btn btn-primary">Filter</button>
                    </div>
                </form>
            </td>
        </tr>
        @foreach (Student student in Model.Students!)
        {
            <tr>
                <td>
                    <a asp-area="" asp-controller="Student" asp-action="Info" asp-route-id="@student.Id">
                        @student.Id
                    </a>
                </td>
                <td>@student.Name</td>
                <td>@student.Group!.Name</td>
                <td>@student.Subjects?.Count</td>
                <td><a asp-controller="Home" asp-action="Index" asp-route-id="@student.Id">Delete</a></td>
            </tr>
        }
        </tbody>
    </table>
</div>

MPP/Lab4/Lab4/Views/Progress/Index.cshtml
@{
    ViewData["Title"] = "Create progress";
}

<form method="post">
    <div>
        <label></label>
    </div>
</form>

MPP/Lab4/Lab4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Lab4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Lab4.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab4</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Lab4
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MPP/Lab4/Lab4/Views/Student/Index.cshtml
@model CreateStudentViewModel

@{
    ViewData["Title"] = "Create Student";
}

<form method="post">
    <div class="form">
        <label class="form-label" for="name">Student Name</label>
        <input class="form-control" type="text" name="name" id="name" />
        <span asp-validation-for="Name" class="text-danger"></span><br />
        <select class="form-control"
                asp-items="@(new SelectList(Model.Groups, "Id", "Name"))"
                name="selectedGroupId"
                id="selectedGroupId">
        </select>
        <span asp-validation-for="SelectedGroupId" class="text-danger"></span><br />
        <button type="submit" class="btn btn-primary mt-2">Create</button>
    </div>
</form>

MPP/Lab4/Lab4/Views/Student/Info.cshtml
@using DAL.Models
@model StudentInfoViewModel

@{
    ViewData["Title"] = "Student Info";
}

<div class="row">
    <div class="col-12">
        <h2>Student Info: @Model.Student?.Id</h2>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-6">
        <h3>@Model.Student?.Name</h3>
    </div>
    <div class="col-6">
        <h4>@Model.Student?.Group?.Name</h4>
    </div>
</div>
<h5>Subjects</h5>
@foreach (Subject subject in Model.Student?.Subjects!)
{
    <div class="row">
        <div class="col-6">
            <p>@subject.Id</p>
        </div>
        <div class="col-6">
            <p>@subject.Name</p>
        </div>
    </div>
}
<div class="row mt-5">
    <h4>Add subject:</h4>
    <div class="col-12">
        <form method="post">
            <div class="form">
                <select class="form-control"
                        asp-items="@(new SelectList(Model.Subjects, "Id", "Name"))"
                        name="subjectId"
                        id="subjectId">
                </select>
                <input type="hidden" name="studentId" id="studentId" value="@Model.Student?.Id" />
            </div>
            <span asp-validation-for="SelectedSubjectId" class="text-danger"></span><br/>
            <button type="submit" class="btn btn-primary mt-2">Add</button>
        </form>
    </div>
</div>